version: '3.8'

services:
  training:
    build: .
    container_name: ml-training-reproducible
    volumes:
      - ../..:/app  # Mount întregul proiect
      - training-models:/app/models
      - training-visualizations:/app/visualizations
      - training-mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=./mlruns
    command: python sources/mlflow_ml_model_web_traffic.py

volumes:
  training-models:
  training-visualizations:
  training-mlruns:
